//Login
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

//Logout
export const USER_LOGOUT = "USER_LOGOUT";

//Register
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";

//Account
export const ACCOUNT_LIST_REQUEST = "ACCOUNT_LIST_REQUEST";
export const ACCOUNT_LIST_SUCCESS = "ACCOUNT_LIST_SUCCESS";
export const ACCOUNT_LIST_FAIL = "ACCOUNT_LIST_FAIL";

export const ACCOUNT_DETAIL_REQUEST = "ACCOUNT_DETAIL_REQUEST";
export const ACCOUNT_DETAIL_SUCCESS = "ACCOUNT_DETAIL_SUCCESS";
export const ACCOUNT_DETAIL_FAIL = "ACCOUNT_DETAIL_FAIL";
export const ACCOUNT_DETAIL_RESET = "ACCOUNT_DETAIL_RESET";

export const ACCOUNT_UPDATE_REQUEST = "ACCOUNT_UPDATE_REQUEST";
export const ACCOUNT_UPDATE_SUCCESS = "ACCOUNT_UPDATE_SUCCESS";
export const ACCOUNT_UPDATE_FAIL = "ACCOUNT_UPDATE_FAIL";
export const ACCOUNT_UPDATE_RESET = "ACCOUNT_UPDATE_RESET";

//User
export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

//Category
export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";

export const CATEGORY_DETAILS_REQUEST = "CATEGORY_DETAILS_REQUEST";
export const CATEGORY_DETAILS_SUCCESS = "CATEGORY_DETAILS_SUCCESS";
export const CATEGORY_DETAILS_STOP = "CATEGORY_DETAILS_STOP";
export const CATEGORY_DETAILS_FAIL = "CATEGORY_DETAILS_FAIL";

export const CATEGORY_CREATE_REQUEST = "CATEGORY_CREATE_REQUEST";
export const CATEGORY_CREATE_SUCCESS = "CATEGORY_CREATE_SUCCESS";
export const CATEGORY_CREATE_FAIL = "CATEGORY_CREATE_FAIL";
export const CATEGORY_CREATE_RESET = "CATEGORY_CREATE_RESET";

export const CATEGORY_UPDATE_REQUEST = "CATEGORY_UPDATE_REQUEST";
export const CATEGORY_UPDATE_SUCCESS = "CATEGORY_UPDATE_SUCCESS";
export const CATEGORY_UPDATE_FAIL = "CATEGORY_UPDATE_FAIL";
export const CATEGORY_UPDATE_RESET = "CATEGORY_UPDATE_RESET";

//Product
export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";
export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";
export const PRODUCT_UPDATE_RESET = "PRODUCT_UPDATE_RESET";

//Image
export const IMAGE_LIST_REQUEST = "IMAGE_LIST_REQUEST";
export const IMAGE_LIST_SUCCESS = "IMAGE_LIST_SUCCESS";
export const IMAGE_LIST_FAIL = "IMAGE_LIST_FAIL";

export const IMAGE_DETAILS_REQUEST = "IMAGE_DETAILS_REQUEST";
export const IMAGE_DETAILS_SUCCESS = "IMAGE_DETAILS_SUCCESS";
export const IMAGE_DETAILS_FAIL = "IMAGE_DETAILS_FAIL";

export const IMAGE_CREATE_REQUEST = "IMAGE_CREATE_REQUEST";
export const IMAGE_CREATE_SUCCESS = "IMAGE_CREATE_SUCCESS";
export const IMAGE_CREATE_FAIL = "IMAGE_CREATE_FAIL";
export const IMAGE_CREATE_RESET = "IMAGE_CREATE_RESET";

export const IMAGE_UPDATE_REQUEST = "IMAGE_UPDATE_REQUEST";
export const IMAGE_UPDATE_SUCCESS = "IMAGE_UPDATE_SUCCESS";
export const IMAGE_UPDATE_FAIL = "IMAGE_UPDATE_FAIL";
export const IMAGE_UPDATE_RESET = "IMAGE_UPDATE_RESET";

//Size
export const SIZE_LIST_REQUEST = "SIZE_LIST_REQUEST";
export const SIZE_LIST_SUCCESS = "SIZE_LIST_SUCCESS";
export const SIZE_LIST_FAIL = "SIZE_LIST_FAIL";

export const SIZE_DETAILS_REQUEST = "SIZE_DETAILS_REQUEST";
export const SIZE_DETAILS_SUCCESS = "SIZE_DETAILS_SUCCESS";
export const SIZE_DETAILS_FAIL = "SIZE_DETAILS_FAIL";

export const SIZE_CREATE_REQUEST = "SIZE_CREATE_REQUEST";
export const SIZE_CREATE_SUCCESS = "SIZE_CREATE_SUCCESS";
export const SIZE_CREATE_FAIL = "SIZE_CREATE_FAIL";
export const SIZE_CREATE_RESET = "SIZE_CREATE_RESET";

export const SIZE_UPDATE_REQUEST = "SIZE_UPDATE_REQUEST";
export const SIZE_UPDATE_SUCCESS = "SIZE_UPDATE_SUCCESS";
export const SIZE_UPDATE_FAIL = "SIZE_UPDATE_FAIL";
export const SIZE_UPDATE_RESET = "SIZE_UPDATE_RESET";

//Cart
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_ITEM_CART = "REMOVE_ITEM_CART"
export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO"

//Wish
export const LINE_ITEM_LIST_REQUEST = "LINE_ITEM_LIST_REQUEST";
export const LINE_ITEM_LIST_SUCCESS = "LINE_ITEM_LIST_SUCCESS";
export const LINE_ITEM_LIST_FAIL = "LINE_ITEM_LIST_FAIL";
export const LINE_ITEM_LIST_RESET = "LINE_ITEM_LIST_RESET";

export const LINE_ITEM_DETAILS_REQUEST = "LINE_ITEM_DETAILS_REQUEST";
export const LINE_ITEM_DETAILS_SUCCESS = "LINE_ITEM_DETAILS_SUCCESS";
export const LINE_ITEM_DETAILS_FAIL = "LINE_ITEM_DETAILS_FAIL";

export const LINE_ITEM_CREATE_REQUEST = "LINE_ITEM_CREATE_REQUEST";
export const LINE_ITEM_CREATE_SUCCESS = "LINE_ITEM_CREATE_SUCCESS";
export const LINE_ITEM_CREATE_FAIL = "LINE_ITEM_CREATE_FAIL";
export const LINE_ITEM_CREATE_RESET = "LINE_ITEM_CREATE_RESET";

export const LINE_ITEM_UPDATE_REQUEST = "LINE_ITEM_UPDATE_REQUEST";
export const LINE_ITEM_UPDATE_SUCCESS = "LINE_ITEM_UPDATE_SUCCESS";
export const LINE_ITEM_UPDATE_FAIL = "LINE_ITEM_UPDATE_FAIL";
export const LINE_ITEM_UPDATE_RESET = "LINE_ITEM_UPDATE_RESET";

export const LINE_ITEM_REMOVE_REQUEST = "LINE_ITEM_REMOVE_REQUEST";
export const LINE_ITEM_REMOVE_SUCCESS = "LINE_ITEM_REMOVE_SUCCESS";
export const LINE_ITEM_REMOVE_FAIL = "LINE_ITEM_REMOVE_FAIL";

export const LINE_ITEM_DELETE_REQUEST = "LINE_ITEM_DELETE_REQUEST";
export const LINE_ITEM_DELETE_SUCCESS = "LINE_ITEM_DELETE_SUCCESS";
export const LINE_ITEM_DELETE_FAIL = "LINE_ITEM_DELETE_FAIL";

//Order
export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const ORDER_LISTBYUSER_REQUEST = "ORDER_LISTBYUSER_REQUEST";
export const ORDER_LISTBYUSER_SUCCESS = "ORDER_LISTBYUSER_SUCCESS";
export const ORDER_LISTBYUSER_FAIL = "ORDER_LISTBYUSER_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

export const ORDER_UPDATE_REQUEST = "ORDER_UPDATE_REQUEST";
export const ORDER_UPDATE_SUCCESS = "ORDER_UPDATE_SUCCESS";
export const ORDER_UPDATE_FAIL = "ORDER_UPDATE_FAIL";
export const ORDER_UPDATE_RESET = "ORDER_UPDATE_RESET";